name: tryon_stylist
description: "Virtual try-on and stylist app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  image_picker: ^1.2.1
  provider: ^6.0.0
  web_socket_channel: ^2.4.0
  google_sign_in: ^7.2.0
  crypto: ^3.0.3
  path_provider: ^2.1.5
  path: ^1.9.1
  shared_preferences: ^2.5.3
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  google_mobile_ads: ^5.2.0
  share_plus: ^12.0.1
  gal: ^2.3.0
  image_cropper: ^8.0.2
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
